class Cart_locators:
    Cart_link = "//a[@id='cartur']"
    Oreder_place_button = "//button[contains(text(),'Place Order')]"
    Name_field = "//input[@id='name']"
    Country_field = "//input[@id='country']"
    City_field = "//input[@id='city']"
    Credit_card = "//input[@id='card']"
    Month_field = "//input[@id='month']"
    Year_feild = "//input[@id='year']"
    Purchase_button = "//button[contains(text(),'Purchase')]"
    Close_field = "//body/div[@id='orderModal']/div[1]/div[1]/div[3]/button[1]"
    Delet_order = "//a[contains(text(),'Delete')]"
    Text_success = "//h2[contains(text(),'Thank you for your purchase!')]"
    Ok_button = "//body[1]/div[11]/p[1]/br[2]"