class aboutUS_locators:
    URL_demo = "https://www.demoblaze.com/index.html"
    About_Us_Page_link = "//a[contains(text(),'About us')]"
    #Viedo_modal_button = "/html/body/div[5]/div/div/div[2]/form/div/div/button"
    Viedo_play_button = "/html/body/div[4]/div/div/div[2]/form/div/div/button"
    Viedo_pause_button = "//body/div[@id='videoModal']/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[4]/button"
    Viedo_speaker_button = "//body/div[@id='videoModal']/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[4]/div[1]/button"
    Viedo_timing_button = "//span[contains(text(),'18:38')]"
    Viedo_exit_picture_button = "//body/div[@id='videoModal']/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[4]/button"
    Viedo_fullScreen_button = "//body/div[@id='videoModal']/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[4]/button"
    Viedo_close_button = "//body/div[@id='videoModal']/div[1]/div[1]/div[3]/button[1]"
